// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Assignment
    {
        public Assignment()
        {
            CitizenAssignment = new HashSet<CitizenAssignment>();
        }

        public int Id { get; set; }
        public DateTime DayOfAssignment { get; set; }
        public DateTime TimeFrameStart { get; set; }
        public DateTime TimeFrameEnd { get; set; }
        public int AssignmentTypeId { get; set; }

        public virtual AssignmentType AssignmentType { get; set; }
        public virtual ICollection<CitizenAssignment> CitizenAssignment { get; set; }
    }
}