// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class AssignmentType
    {
        public AssignmentType()
        {
            Assignment = new HashSet<Assignment>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string AssignmentTypeDescription { get; set; }
        public int DurationInSeconds { get; set; }

        public virtual ICollection<Assignment> Assignment { get; set; }
    }
}