// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Assignment
    {
        public Assignment()
        {
            EmployeeRoute = new HashSet<EmployeeRoute>();
        }

        public int Id { get; set; }
        public int CitizenId { get; set; }
        public int TimeFrameId { get; set; }
        public int EmployeeTypeMasterId { get; set; }
        public int EmployeeTypeSlaveId { get; set; }
        public int AssignmentTypeId { get; set; }
        public int? EmployeeSkillId { get; set; }

        public virtual AssignmentType AssignmentType { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual EmployeeType EmployeeTypeMaster { get; set; }
        public virtual EmployeeType EmployeeTypeSlave { get; set; }
        public virtual TimeFrame TimeFrame { get; set; }
        public virtual ICollection<EmployeeRoute> EmployeeRoute { get; set; }
    }
}