// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Citizen
    {
        public Citizen()
        {
            CitizenAssignment = new HashSet<CitizenAssignment>();
        }

        public int Id { get; set; }
        public string CitizenName { get; set; }
        public int ResidenceId { get; set; }

        public virtual Residence Residence { get; set; }
        public virtual ICollection<CitizenAssignment> CitizenAssignment { get; set; }
    }
}