// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class CitizenAssignment
    {
        public CitizenAssignment()
        {
            EmployeeRoute = new HashSet<EmployeeRoute>();
            EmployeeRouteNavigation = new HashSet<EmployeeRoute>();
        }

        public int Id { get; set; }
        public int CitizenId { get; set; }
        public int AssignmentId { get; set; }
        public int EmployeeTypeMaster { get; set; }
        public int EmployeeTypeSlave { get; set; }
        public int EmployeeSkillId { get; set; }

        public virtual Assignment Assignment { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual EmployeeSkill EmployeeSkill { get; set; }
        public virtual EmployeeType EmployeeTypeMasterNavigation { get; set; }
        public virtual EmployeeType EmployeeTypeSlaveNavigation { get; set; }
        public virtual ICollection<EmployeeRoute> EmployeeRoute { get; set; }

        public virtual ICollection<EmployeeRoute> EmployeeRouteNavigation { get; set; }
    }
}