// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            AssignmentEmployeeTypeMaster = new HashSet<Assignment>();
            AssignmentEmployeeTypeSlave = new HashSet<Assignment>();
            Employee = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string Title { get; set; }

        public virtual ICollection<Assignment> AssignmentEmployeeTypeMaster { get; set; }
        public virtual ICollection<Assignment> AssignmentEmployeeTypeSlave { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}