// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Employee
    {
        public Employee()
        {
            EmployeeSkill = new HashSet<EmployeeSkill>();
            EmployeeStatementPeriod = new HashSet<EmployeeStatementPeriod>();
            EmployeeRoute = new HashSet<EmployeeRoute>();
            Preference = new HashSet<Preference>();
        }

        public int Id { get; set; }
        public string Initials { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeName { get; set; }
        public int WeeklyWorkingHours { get; set; }
        public int EmployeeTypeId { get; set; }
        public int SkillId { get; set; }

        public virtual ICollection<EmployeeSkill> EmployeeSkill { get; set; }
        public virtual ICollection<EmployeeStatementPeriod> EmployeeStatementPeriod { get; set; }

        public virtual ICollection<EmployeeRoute> EmployeeRoute { get; set; }
        public virtual ICollection<Preference> Preference { get; set; }
    }
}