// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class EmployeeRoute
    {
        public EmployeeRoute()
        {
            CitizenAssignmentNavigation = new HashSet<CitizenAssignment>();
            Employee = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public int CitizenAssignmentId { get; set; }

        public virtual CitizenAssignment CitizenAssignment { get; set; }

        public virtual ICollection<CitizenAssignment> CitizenAssignmentNavigation { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}