// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Employee
    {
        public Employee()
        {
            EmployeeEmployeeRoute = new HashSet<EmployeeEmployeeRoute>();
            EmployeePreference = new HashSet<EmployeePreference>();
            EmployeeSkill = new HashSet<EmployeeSkill>();
            EmployeeStatementPeriod = new HashSet<EmployeeStatementPeriod>();
        }

        public int Id { get; set; }
        public string Initials { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeName { get; set; }
        public int WeeklyWorkingHours { get; set; }
        public int EmployeeTypeId { get; set; }
        public int? SkillId { get; set; }

        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<EmployeeEmployeeRoute> EmployeeEmployeeRoute { get; set; }
        public virtual ICollection<EmployeePreference> EmployeePreference { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkill { get; set; }
        public virtual ICollection<EmployeeStatementPeriod> EmployeeStatementPeriod { get; set; }
    }
}