// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            CitizenAssignmentEmployeeTypeMasterNavigation = new HashSet<CitizenAssignment>();
            CitizenAssignmentEmployeeTypeSlaveNavigation = new HashSet<CitizenAssignment>();
        }

        public int Id { get; set; }
        public string Title { get; set; }

        public virtual ICollection<CitizenAssignment> CitizenAssignmentEmployeeTypeMasterNavigation { get; set; }
        public virtual ICollection<CitizenAssignment> CitizenAssignmentEmployeeTypeSlaveNavigation { get; set; }
    }
}