// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Preference
    {
        public Preference()
        {
            Employee = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public int WorkingTimespanId { get; set; }
        public int DayTypeId { get; set; }

        public virtual DayType DayType { get; set; }
        public virtual WorkingTimespan WorkingTimespan { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
    }
}