// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class Residence
    {
        public Residence()
        {
            Citizen = new HashSet<Citizen>();
            DistanceResidenceOne = new HashSet<Distance>();
            DistanceResidenceTwo = new HashSet<Distance>();
        }

        public int Id { get; set; }
        public string CitizenResidence { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public virtual ICollection<Citizen> Citizen { get; set; }
        public virtual ICollection<Distance> DistanceResidenceOne { get; set; }
        public virtual ICollection<Distance> DistanceResidenceTwo { get; set; }
    }
}