// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Domain.Entities
{
    public partial class TimeFrame
    {
        public TimeFrame()
        {
            Assignment = new HashSet<Assignment>();
        }

        public int Id { get; set; }
        public DateTime TimeFrameStart { get; set; }
        public DateTime TimeFrameEnd { get; set; }

        public virtual ICollection<Assignment> Assignment { get; set; }
    }
}