// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ComfortCare.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace ComfortCare.Data
{
    public partial class ComfortCareDbContext : DbContext
    {
        public ComfortCareDbContext()
        {
        }

        public ComfortCareDbContext(DbContextOptions<ComfortCareDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<AssignmentType> AssignmentType { get; set; }
        public virtual DbSet<Citizen> Citizen { get; set; }
        public virtual DbSet<CitizenAssignment> CitizenAssignment { get; set; }
        public virtual DbSet<DayType> DayType { get; set; }
        public virtual DbSet<Distance> Distance { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeRoute> EmployeeRoute { get; set; }
        public virtual DbSet<EmployeeSkill> EmployeeSkill { get; set; }
        public virtual DbSet<EmployeeStatementPeriod> EmployeeStatementPeriod { get; set; }
        public virtual DbSet<EmployeeType> EmployeeType { get; set; }
        public virtual DbSet<Preference> Preference { get; set; }
        public virtual DbSet<Residence> Residence { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<StatementPeriod> StatementPeriod { get; set; }
        public virtual DbSet<TimeRegistration> TimeRegistration { get; set; }
        public virtual DbSet<WorkingTimespan> WorkingTimespan { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Assignment>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AssignmentTypeId).HasColumnName("AssignmentTypeID");

                entity.Property(e => e.DayOfAssignment).HasColumnType("datetime");

                entity.Property(e => e.TimeFrameEnd).HasColumnType("datetime");

                entity.Property(e => e.TimeFrameStart).HasColumnType("datetime");

                entity.HasOne(d => d.AssignmentType)
                    .WithMany(p => p.Assignment)
                    .HasForeignKey(d => d.AssignmentTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Assignmen__Assig__412EB0B6");
            });

            modelBuilder.Entity<AssignmentType>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AssignmentTypeDescription)
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Citizen>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CitizenName)
                    .IsRequired()
                    .HasMaxLength(64)
                    .IsUnicode(false);

                entity.Property(e => e.ResidenceId).HasColumnName("ResidenceID");

                entity.HasOne(d => d.Residence)
                    .WithMany(p => p.Citizen)
                    .HasForeignKey(d => d.ResidenceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Citizen__Residen__3A81B327");
            });

            modelBuilder.Entity<CitizenAssignment>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AssignmentId).HasColumnName("AssignmentID");

                entity.Property(e => e.CitizenId).HasColumnName("CitizenID");

                entity.Property(e => e.EmployeeSkillId).HasColumnName("EmployeeSkillID");

                entity.HasOne(d => d.Assignment)
                    .WithMany(p => p.CitizenAssignment)
                    .HasForeignKey(d => d.AssignmentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CitizenAs__Assig__440B1D61");

                entity.HasOne(d => d.Citizen)
                    .WithMany(p => p.CitizenAssignment)
                    .HasForeignKey(d => d.CitizenId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CitizenAs__Citiz__4316F928");

                entity.HasOne(d => d.EmployeeSkill)
                    .WithMany(p => p.CitizenAssignment)
                    .HasForeignKey(d => d.EmployeeSkillId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CitizenAs__Emplo__46E78A0C");

                entity.HasOne(d => d.EmployeeTypeMasterNavigation)
                    .WithMany(p => p.CitizenAssignmentEmployeeTypeMasterNavigation)
                    .HasForeignKey(d => d.EmployeeTypeMaster)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CitizenAs__Emplo__44FF419A");

                entity.HasOne(d => d.EmployeeTypeSlaveNavigation)
                    .WithMany(p => p.CitizenAssignmentEmployeeTypeSlaveNavigation)
                    .HasForeignKey(d => d.EmployeeTypeSlave)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CitizenAs__Emplo__45F365D3");
            });

            modelBuilder.Entity<DayType>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.WorkingDayType)
                    .IsRequired()
                    .HasMaxLength(254)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Distance>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ResidenceOneId).HasColumnName("ResidenceOneID");

                entity.Property(e => e.ResidenceTwoId).HasColumnName("ResidenceTwoID");

                entity.HasOne(d => d.ResidenceOne)
                    .WithMany(p => p.DistanceResidenceOne)
                    .HasForeignKey(d => d.ResidenceOneId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Distance__Reside__4AB81AF0");

                entity.HasOne(d => d.ResidenceTwo)
                    .WithMany(p => p.DistanceResidenceTwo)
                    .HasForeignKey(d => d.ResidenceTwoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Distance__Reside__4BAC3F29");
            });

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.EmployeeName)
                    .IsRequired()
                    .HasMaxLength(64)
                    .IsUnicode(false);

                entity.Property(e => e.EmployeePassword)
                    .IsRequired()
                    .HasMaxLength(64)
                    .IsUnicode(false);

                entity.Property(e => e.EmployeeTypeId).HasColumnName("EmployeeTypeID");

                entity.Property(e => e.Initials)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false);

                entity.Property(e => e.SkillId).HasColumnName("SkillID");

                entity.HasMany(d => d.EmployeeRoute)
                    .WithMany(p => p.Employee)
                    .UsingEntity<Dictionary<string, object>>(
                        "EmployeeWorkSchedule",
                        l => l.HasOne<EmployeeRoute>().WithMany().HasForeignKey("EmployeeRouteId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__EmployeeW__Emplo__5629CD9C"),
                        r => r.HasOne<Employee>().WithMany().HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__EmployeeW__Emplo__5535A963"),
                        j =>
                        {
                            j.HasKey("EmployeeId", "EmployeeRouteId");

                            j.ToTable("EmployeeWorkSchedule");

                            j.IndexerProperty<int>("EmployeeId").HasColumnName("EmployeeID");

                            j.IndexerProperty<int>("EmployeeRouteId").HasColumnName("EmployeeRouteID");
                        });

                entity.HasMany(d => d.Preference)
                    .WithMany(p => p.Employee)
                    .UsingEntity<Dictionary<string, object>>(
                        "EmployeePreference",
                        l => l.HasOne<Preference>().WithMany().HasForeignKey("PreferenceId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__EmployeeP__Prefe__59063A47"),
                        r => r.HasOne<Employee>().WithMany().HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__EmployeeP__Emplo__5812160E"),
                        j =>
                        {
                            j.HasKey("EmployeeId", "PreferenceId");

                            j.ToTable("EmployeePreference");

                            j.IndexerProperty<int>("EmployeeId").HasColumnName("EmployeeID");

                            j.IndexerProperty<int>("PreferenceId").HasColumnName("PreferenceID");
                        });
            });

            modelBuilder.Entity<EmployeeRoute>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CitizenAssignmentId).HasColumnName("CitizenAssignmentID");

                entity.HasOne(d => d.CitizenAssignment)
                    .WithMany(p => p.EmployeeRoute)
                    .HasForeignKey(d => d.CitizenAssignmentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EmployeeR__Citiz__48CFD27E");

                entity.HasMany(d => d.CitizenAssignmentNavigation)
                    .WithMany(p => p.EmployeeRouteNavigation)
                    .UsingEntity<Dictionary<string, object>>(
                        "RouteCitizenAssignment",
                        l => l.HasOne<CitizenAssignment>().WithMany().HasForeignKey("CitizenAssignmentId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__RouteCiti__Citiz__534D60F1"),
                        r => r.HasOne<EmployeeRoute>().WithMany().HasForeignKey("EmployeeRouteId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__RouteCiti__Emplo__52593CB8"),
                        j =>
                        {
                            j.HasKey("EmployeeRouteId", "CitizenAssignmentId");

                            j.ToTable("RouteCitizenAssignment");

                            j.IndexerProperty<int>("EmployeeRouteId").HasColumnName("EmployeeRouteID");

                            j.IndexerProperty<int>("CitizenAssignmentId").HasColumnName("CitizenAssignmentID");
                        });
            });

            modelBuilder.Entity<EmployeeSkill>(entity =>
            {
                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("ID");

                entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");

                entity.Property(e => e.SkillId).HasColumnName("SkillID");

                entity.HasOne(d => d.Employee)
                    .WithMany(p => p.EmployeeSkill)
                    .HasForeignKey(d => d.EmployeeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EmployeeS__Emplo__3D5E1FD2");

                entity.HasOne(d => d.Skill)
                    .WithMany(p => p.EmployeeSkill)
                    .HasForeignKey(d => d.SkillId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EmployeeS__Skill__3E52440B");
            });

            modelBuilder.Entity<EmployeeStatementPeriod>(entity =>
            {
                entity.HasKey(e => new { e.EmployeeId, e.StatementPeriodId });

                entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");

                entity.Property(e => e.StatementPeriodId).HasColumnName("StatementPeriodID");

                entity.Property(e => e.TimeRegistrationId).HasColumnName("TimeRegistrationID");

                entity.HasOne(d => d.Employee)
                    .WithMany(p => p.EmployeeStatementPeriod)
                    .HasForeignKey(d => d.EmployeeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EmployeeS__Emplo__5BE2A6F2");

                entity.HasOne(d => d.StatementPeriod)
                    .WithMany(p => p.EmployeeStatementPeriod)
                    .HasForeignKey(d => d.StatementPeriodId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EmployeeS__State__5CD6CB2B");

                entity.HasOne(d => d.TimeRegistration)
                    .WithMany(p => p.EmployeeStatementPeriod)
                    .HasForeignKey(d => d.TimeRegistrationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__EmployeeS__TimeR__5DCAEF64");
            });

            modelBuilder.Entity<EmployeeType>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Preference>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.DayTypeId).HasColumnName("DayTypeID");

                entity.Property(e => e.WorkingTimespanId).HasColumnName("WorkingTimespanID");

                entity.HasOne(d => d.DayType)
                    .WithMany(p => p.Preference)
                    .HasForeignKey(d => d.DayTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Preferenc__DayTy__5070F446");

                entity.HasOne(d => d.WorkingTimespan)
                    .WithMany(p => p.Preference)
                    .HasForeignKey(d => d.WorkingTimespanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Preferenc__Worki__4F7CD00D");
            });

            modelBuilder.Entity<Residence>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CitizenResidence)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.Latitude)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.Longitude)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Skill>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.SkillDescription)
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<StatementPeriod>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.EndDate).HasColumnType("datetime");

                entity.Property(e => e.StartDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<TimeRegistration>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.DateStartTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<WorkingTimespan>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.TimeEnd).HasColumnType("datetime");

                entity.Property(e => e.TimeStart).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}