// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Data.Models
{
    public partial class Citizen
    {
        public Citizen()
        {
            Assignment = new HashSet<Assignment>();
        }

        public int Id { get; set; }
        public string CitizenName { get; set; }
        public int ResidenceId { get; set; }

        public virtual Residence Residence { get; set; }
        public virtual ICollection<Assignment> Assignment { get; set; }
    }
}