// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Data.Models
{
    public partial class EmployeeRoute
    {
        public EmployeeRoute()
        {
            RouteAssignment = new HashSet<RouteAssignment>();
        }

        public int Id { get; set; }
        public int EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual ICollection<RouteAssignment> RouteAssignment { get; set; }
    }
}