// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Data.Models
{
    public partial class StatementPeriod
    {
        public StatementPeriod()
        {
            EmployeeStatementPeriod = new HashSet<EmployeeStatementPeriod>();
        }

        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public virtual ICollection<EmployeeStatementPeriod> EmployeeStatementPeriod { get; set; }
    }
}