// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Data.Models
{
    public partial class TimeFrame
    {
        public TimeFrame()
        {
            AssignmentType = new HashSet<AssignmentType>();
        }

        public int Id { get; set; }
        public DateTime TimeFrameStart { get; set; }
        public DateTime TimeFrameEnd { get; set; }

        public virtual ICollection<AssignmentType> AssignmentType { get; set; }
    }
}