// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Data.Models
{
    public partial class TimeRegistration
    {
        public TimeRegistration()
        {
            EmployeeStatementPeriod = new HashSet<EmployeeStatementPeriod>();
        }

        public int Id { get; set; }
        public DateTime DateStartTime { get; set; }
        public double WorkingHours { get; set; }

        public virtual ICollection<EmployeeStatementPeriod> EmployeeStatementPeriod { get; set; }
    }
}