// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComfortCare.Data.Models
{
    public partial class WorkingTimespan
    {
        public WorkingTimespan()
        {
            Preference = new HashSet<Preference>();
        }

        public int Id { get; set; }
        public DateTime TimeStart { get; set; }
        public DateTime TimeEnd { get; set; }

        public virtual ICollection<Preference> Preference { get; set; }
    }
}